name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -v

      - name: Set up environment variables
        run: echo "API_TOKEN_GTH=${{ secrets.API_TOKEN_GTH }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: mvn clean install --no-transfer-progress --quiet

      - name: Print environment variables
        run: env

      - name: Print test reports
        run: ls -R target/surefire-reports

      - name: Run tests with debug logging
        run: mvn test -X
